create table data_pasien(
    no int (11) PRIMARY KEY AUTO_INCREMENT,
    nama varchar(30),
    alamat varchar(50),
    usia int (3),
    jk ENUM('L','P') ,
    pekerjaan enum( 'PNS','Wiraswasta','Pensiunan','Honorer','Dokter','Dosen','Petani','Buruh','IRT',
     'Pedagang','Supir','Nelayan','Lainnya','Tidak diketahui'),
    riwayat_keluarga ENUM('Tidak_ada', 'Ada'),
    riwayat_jantung ENUM('Tidak_ada', 'Ada'),
    r_dm ENUM('Tidak_ada', 'Ada'),
    r_ht ENUM('Tidak_ada', 'Ada'),
    r_chol ENUM('Tidak_ada', 'Ada'),
    obesitas ENUM('Tidak', 'Iya'),
    sistolik double,
    diastolik double,
    ldl double,
    hdl double,
    chol double,
    trig double,
    glu double,
    elevasi_st ENUM('Tidak_ada','Ada'),
    enzim_jantung ENUM('Normal','Meningkat'),
    kasus varchar(10),
    tipe ENUM('data_latih','data_uji') default 'data_latih'
)
