CREATE table data_normalisasi (
    no int (11) PRIMARY KEY AUTO_INCREMENT,
    no_data int (11) ,
    x1_usia double,
    x2_jk int(1),
    x3_pekerjaan double ,
    x4_riwayat_keluarga int(1),
    x5_riwayat_jantung int(1),
    x6_r_dm int(1),
    x7_r_ht int(1),
    x8_r_chol int(1),
    x9_obesitas int(1),
    x10_sistolik double,
    x11_diastolik double,
    x12_ldl double,
    x13_hdl double,
    x14_chol double,
    x15_trig double,
    x16_glu double,
    x17_elevasi_st int(1),
    x18_enzim_jantung int(1),
    kelas_kasus ENUM('1','2','3'),
    FOREIGN KEY (no_data) REFERENCES data_pasien (no)
)
